version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
    environment:
      - DB_HOST=database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=symfony_crud
      - POSTGRES_USER=symfony_crud
      - POSTGRES_PASSWORD=password
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=5432